# Generated by Django 3.2.19 on 2023-05-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20230508_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='to_user',
            field=models.IntegerField(default=0),
        ),
    ]
